/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacud.view;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javacrud.model.Utilisateur;
import javacrud.control.UtilisateurDAOImp;
import java.util.TreeMap;
import javacrud.model.Commune;
//import javacrud.view.SelectVille;

/**
 *
 * @author s.lussiez
 */
public class UtilCrud extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    //LinkedList<Utilisateur> lesUtilisateurs = new LinkedList<>();
    TreeMap<String, Utilisateur> lesUtilisateurs = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    UtilisateurDAOImp dao = new UtilisateurDAOImp();
    String uiNumpost; 
    private Object[] selectedVille;
    /**
     * Creates new form UtilCrud
     */
    public UtilCrud() {
        initComponents();
        jLabel9.setText("Veuillez choisir un utilisateur dans le tableau de droite ou saisir les données à créer");
        chargerLesUtilisateurs();        
    }
    
    private void chargerLesUtilisateurs(){
        lesUtilisateurs.clear();
        lesUtilisateurs = dao.list();
        chargerTableauUtilisateurs();
    }
    
    private void chargerTableauUtilisateurs(){
        DefaultTableModel uiTable = (DefaultTableModel)tbUtilisateurs.getModel();
        int j = uiTable.getRowCount();
        for (int i = j-1; i>=0 ; i--){
            uiTable.removeRow(i);
        }
        for (String pseudo : lesUtilisateurs.keySet()) {
            Utilisateur unUtilisateur = lesUtilisateurs.get(pseudo);
            Object[] row = new Object[3];
            row[0] = unUtilisateur.getUtNom();
            row[1] = unUtilisateur.getUtPrenom();
            row[2] = unUtilisateur.getUtPseudo();
        
            uiTable.addRow(row);        
        }
        
    }
    
    public void changerSelectUt(){
        //pointer sur la colonne sélectionnée
        int i = tbUtilisateurs.getSelectedRow();
        //récupérer les données utilisateurs
        //utiliser les données du tableau ou ...
        TableModel model = tbUtilisateurs.getModel();
        Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i,2).toString());
        uiNom.setText(unUtilisateur.getUtNom());
        uiPrenom.setText(unUtilisateur.getUtPrenom());
        uiPseudo.setText(unUtilisateur.getUtPseudo());
        uiMail.setText(unUtilisateur.getUtMail());
        uiMP.setText(unUtilisateur.getUtMp());
        uiPhrase.setText(unUtilisateur.getUtPhrase());
        uiAdr1.setText(unUtilisateur.getUtAdr1());
        uiAdr2.setText(unUtilisateur.getUtAdr2());
        uiCdpost.setText(unUtilisateur.getUtCdpost());
        uiCommune.setText(unUtilisateur.getUtCommune());
        
    }
    //afficher un message
    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText(msg);
    }
    //show an error alert
    public void alert(String msg, String titre) {
        JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText(msg);
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUtilisateurs = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ville = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        uiNom = new javax.swing.JTextField();
        uiPrenom = new javax.swing.JTextField();
        uiPseudo = new javax.swing.JTextField();
        uiMail = new javax.swing.JTextField();
        uiMP = new javax.swing.JTextField();
        uiAdr1 = new javax.swing.JTextField();
        uiAdr2 = new javax.swing.JTextField();
        uiCdpost = new javax.swing.JTextField();
        uiCommune = new javax.swing.JTextField();
        uiPhrase = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\java_64.png")); // NOI18N
        jLabel1.setText(" Crud Simplifie : Gestion des utilisateurs et autres ressources");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 70);

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Utilisateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUtilisateurs.setOpaque(false);
        tbUtilisateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUtilisateursMouseClicked(evt);
            }
        });
        tbUtilisateurs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUtilisateursKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbUtilisateurs);
        if (tbUtilisateurs.getColumnModel().getColumnCount() > 0) {
            tbUtilisateurs.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 510, 400);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        label2.setText("Nom");
        jPanel1.add(label2);
        label2.setBounds(10, 20, 70, 20);

        label3.setText("Prénom");
        jPanel1.add(label3);
        label3.setBounds(10, 50, 70, 20);

        label4.setText("Utilisateur");
        jPanel1.add(label4);
        label4.setBounds(10, 90, 80, 20);

        label5.setText("Mail");
        jPanel1.add(label5);
        label5.setBounds(10, 120, 50, 20);

        label6.setText("Mot de passe");
        jPanel1.add(label6);
        label6.setBounds(10, 150, 90, 20);

        jLabel7.setText("Adresse");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 220, 80, 20);

        jLabel8.setText("Code postal");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 290, 90, 20);

        Ville.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\eye_20.png")); // NOI18N
        Ville.setText("Ville");
        Ville.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VilleMouseClicked(evt);
            }
        });
        jPanel1.add(Ville);
        Ville.setBounds(10, 320, 90, 29);

        createButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\plus_20.png")); // NOI18N
        createButton.setText("Creer");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        jPanel1.add(createButton);
        createButton.setBounds(10, 360, 90, 29);

        Modifier.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\pencil_20.png")); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierMouseClicked(evt);
            }
        });
        jPanel1.add(Modifier);
        Modifier.setBounds(105, 360, 95, 29);

        Supprimer.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\minus_20.png")); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });
        jPanel1.add(Supprimer);
        Supprimer.setBounds(210, 360, 110, 30);

        Refresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\eye-slash_20.png")); // NOI18N
        Refresh.setText("Nouveau");
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        jPanel1.add(Refresh);
        Refresh.setBounds(350, 360, 110, 29);

        uiNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiNomActionPerformed(evt);
            }
        });
        jPanel1.add(uiNom);
        uiNom.setBounds(110, 10, 270, 30);
        jPanel1.add(uiPrenom);
        uiPrenom.setBounds(110, 40, 270, 30);
        jPanel1.add(uiPseudo);
        uiPseudo.setBounds(110, 80, 270, 30);
        jPanel1.add(uiMail);
        uiMail.setBounds(110, 110, 350, 30);
        jPanel1.add(uiMP);
        uiMP.setBounds(110, 140, 150, 30);
        jPanel1.add(uiAdr1);
        uiAdr1.setBounds(110, 210, 350, 30);
        jPanel1.add(uiAdr2);
        uiAdr2.setBounds(110, 240, 350, 30);
        jPanel1.add(uiCdpost);
        uiCdpost.setBounds(110, 280, 140, 30);
        jPanel1.add(uiCommune);
        uiCommune.setBounds(110, 320, 350, 30);
        jPanel1.add(uiPhrase);
        uiPhrase.setBounds(110, 170, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(520, 70, 480, 400);

        jPanel2.setOpaque(false);

        Exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\escape_20.png")); // NOI18N
        Exit.setText("Quitter");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\question-circle_20.png")); // NOI18N
        jButton7.setText("Aide");

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\info-circle_20.png")); // NOI18N
        jButton8.setText("Au sujet");

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\envelope_20.png")); // NOI18N
        jButton9.setText("Mail");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Message");

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\wrench._20.png")); // NOI18N
        jButton10.setText("Paramètre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(17, 17, 17)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(17, 17, 17)
                .addComponent(Exit)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(427, 427, 427))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(Exit)
                    .addComponent(jButton10))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 470, 1000, 80);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\s.lussiez\\Downloads\\back_ec.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1010, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiNomActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tbUtilisateursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUtilisateursMouseClicked
        // TODO add your handling code here:
        changerSelectUt();
    }//GEN-LAST:event_tbUtilisateursMouseClicked

    private void tbUtilisateursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUtilisateursKeyReleased
        // TODO add your handling code here:
        changerSelectUt();
    }//GEN-LAST:event_tbUtilisateursKeyReleased

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        // TODO add your handling code here:
        Utilisateur utilisateur = new Utilisateur();
        
        utilisateur.setUtPseudo(uiPseudo.getText());
        utilisateur.setUtNom(uiNom.getText());
        utilisateur.setUtPrenom(uiPrenom.getText());
        utilisateur.setUtMail(uiMail.getText());
        utilisateur.setUtMp(uiMP.getText());
        String Phrase = utilisateur.updateMp(uiMP.getText());
        utilisateur.setUtPhrase(Phrase);
        utilisateur.setUtAdr1(uiAdr1.getText());
        utilisateur.setUtAdr2(uiAdr2.getText());
        utilisateur.setUtCdpost(uiCdpost.getText());
        String numPost = "0";
        utilisateur.setUtNumpost(numPost);
        utilisateur.setUtCommune(uiCommune.getText());
        lesUtilisateurs.put(utilisateur.getUtPseudo(), utilisateur);
        this.chargerTableauUtilisateurs();
        
        UtilisateurDAOImp utDaoImp = new UtilisateurDAOImp();
        utDaoImp.create(utilisateur);
        
        
        
    }//GEN-LAST:event_createButtonMouseClicked

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        // TODO add your handling code here:
        Utilisateur utilisateurSup = new Utilisateur(); 
        int i = tbUtilisateurs.getSelectedRow();
        TableModel modelSup = tbUtilisateurs.getModel();
        utilisateurSup = lesUtilisateurs.get(modelSup.getValueAt(i,2).toString());
        lesUtilisateurs.remove(utilisateurSup.getUtPseudo(), utilisateurSup);
        UtilisateurDAOImp utilDAOImp = new UtilisateurDAOImp();
        utilDAOImp.delete(utilisateurSup);
        this.chargerTableauUtilisateurs();
        
    }//GEN-LAST:event_SupprimerMouseClicked

    private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked
        // TODO add your handling code here:
        Utilisateur utilisateur = new Utilisateur();
        
        utilisateur.setUtNom(uiNom.getText());
        utilisateur.setUtPrenom(uiPrenom.getText());
        utilisateur.setUtMp(uiMP.getText());
        utilisateur.setUtMail(uiMail.getText());
        String Phrase = utilisateur.updateMp(uiMP.getText());
        utilisateur.setUtPhrase(Phrase);
        utilisateur.setUtAdr1(uiAdr1.getText());
        utilisateur.setUtAdr2(uiAdr2.getText());
        utilisateur.setUtCdpost(uiCdpost.getText());
        utilisateur.setUtNumpost("0");
        //utilisateur.setUtCommune(uiCommune.getText());
        utilisateur.setUtPseudo(uiPseudo.getText());
        
        this.chargerTableauUtilisateurs();
        UtilisateurDAOImp utDaoImp = new UtilisateurDAOImp();
        utDaoImp.update(utilisateur);
    }//GEN-LAST:event_ModifierMouseClicked

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        // TODO add your handling code here:
        uiNom.setText("");
        uiPrenom.setText("");
        uiPseudo.setText("");
        uiMail.setText("");
        uiMP.setText("");
        uiPhrase.setText("");
        uiAdr1.setText("");
        uiAdr2.setText("");
        uiCdpost.setText("");
        uiCommune.setText("");
    }//GEN-LAST:event_RefreshMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void VilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VilleMouseClicked
        // TODO add your handling code here:
        String codePost = uiCdpost.getText().strip();
        if (codePost.matches("[0-9]+") && codePost.length()==5){
            SelectVille city = new SelectVille(new javax.swing.JFrame(), true, uiNumpost, codePost);
            city.setVisible(true);
        }
        else{
            alert("Saisir un code postal à 5 chiffre avant de sélectionner la ville !!!");
            return;
        }            
    }//GEN-LAST:event_VilleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton Ville;
    private javax.swing.JButton createButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JTable tbUtilisateurs;
    private javax.swing.JTextField uiAdr1;
    private javax.swing.JTextField uiAdr2;
    private javax.swing.JTextField uiCdpost;
    private javax.swing.JTextField uiCommune;
    private javax.swing.JTextField uiMP;
    private javax.swing.JTextField uiMail;
    private javax.swing.JTextField uiNom;
    private javax.swing.JTextField uiPhrase;
    private javax.swing.JTextField uiPrenom;
    private javax.swing.JTextField uiPseudo;
    // End of variables declaration//GEN-END:variables
}
